name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.2.5" # match your engine's version

      - name: Install Haxelib libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-ui
          haxelib install hxcpp
          haxelib list

      - name: Setup Android SDK + NDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 30            # Android API version
          ndk: 21.4.7075529        # Compatible NDK
          cmake: 3.10.2.4988404    # Needed for Lime

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Setup Lime Android
        run: haxelib run lime setup android --quiet

      - name: Build APK
        run: haxelib run lime build android -final

      - name: Upload Artifact (APK)
        uses: actions/upload-artifact@v3
        with:
          name: FNF-GoverTX-Android
          path: export/release/android/bin/*.apk
